
services:

  deepfix-server:
    build: .
    image: deepfix-server:latest
    ports:
      - "8844:8844"
      - "5001:5000"
      - "8841:8841"
    env_file:
      - deepfix-server/.env 
    volumes:
      - ./server_logs:/logs
      - ./server_mlflow_data:/mlflow



