services:

  # ===================
  # Reverse Proxy
  # ===================
  traefik:
    image: traefik:v3.6
    container_name: traefik-deepfix
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/certs:/etc/traefik/certs:ro
    labels:
      - "traefik.enable=true"


  deepfix-portal:
    build:
      context: .
      dockerfile: ./packages/deepfix-portal/Dockerfile
    image: deepfix-portal:latest
    restart: unless-stopped
    ports:
      - "3000:5041"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://deepfix-admin:deepfix-fadel841@deepfix-db:5432/deepfix_portal
      - FRONTEND_URL=http://localhost:3000
      - DEEPFIX_SERVER_URL=http://deepfix-server:8844
      - ENVIRONMENT=development
    depends_on:
      - traefik
      - deepfix-server
      - deepfix-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deepfix-portal.rule=Host(`localhost`)"
      - "traefik.http.routers.deepfix-portal.entrypoints=web,websecure"
      - "traefik.http.routers.deepfix-portal.tls=true"
      - "traefik.http.services.deepfix-portal.loadbalancer.server.port=5041"

  deepfix-server:
    build:
      context: .
      dockerfile: ./packages/deepfix-server/Dockerfile
    image: deepfix-server:latest
    env_file:
      - .env
    environment:
      - DEEPFIX_SERVER_DATABASE_URL=sqlite:////app/.deepfix/deepfix_server.db
    restart: unless-stopped

    command: ["deepfix-server", "launch", "-port", "8844", "-host", "0.0.0.0", "-workers", "1", "--reload"]
    ports:
      - "8844:8844"
    #volumes:
    #  - ./server_data/.deepfix:/app/.deepfix
    develop:
      watch:
        - action: sync
          path: ./packages/deepfix-server/src
          target: /app/packages/deepfix-server/src
        - action: sync
          path: ./packages/deepfix-core/src
          target: /app/packages/deepfix-core/src
        - action: sync
          path: ./packages/deepfix-kb/src
          target: /app/packages/deepfix-kb/src
        - action: rebuild
          path: ./packages/deepfix-server/pyproject.toml
        - action: rebuild
          path: ./packages/deepfix-core/pyproject.toml
        - action: rebuild
          path: ./packages/deepfix-kb/pyproject.toml


  deepfix-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: deepfix-admin
      POSTGRES_PASSWORD: deepfix-fadel841
      POSTGRES_DB: deepfix_portal
    ports:
      - "5444:5432"
    volumes:
      - ./server_data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deepfix-admin -d deepfix_portal"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
