"""Add job tracking fields to RequestLog

Revision ID: 7a2ff7d0c32d
Revises: 003_add_dspy_cache
Create Date: 2026-04-23 19:28:16.095542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2ff7d0c32d'
down_revision = '003_add_dspy_cache'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('response_summary', sa.Text(), nullable=True))
    op.add_column('request_logs', sa.Column('remote_job_id', sa.String(), nullable=True))
    op.add_column('request_logs', sa.Column('job_status', sa.String(), nullable=True))
    op.add_column('request_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_request_logs_remote_job_id'), 'request_logs', ['remote_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_remote_job_id'), table_name='request_logs')
    op.drop_column('request_logs', 'error_message')
    op.drop_column('request_logs', 'job_status')
    op.drop_column('request_logs', 'remote_job_id')
    op.drop_column('request_logs', 'response_summary')
    # ### end Alembic commands ###
